services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=testdata'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5000:5432'
    expose:
      - '5000'